Repository softeerbootcamp/Team2-CarBook, pull requests merged in 2023-02, with the labels that each got.

#42 docs: README.md ERD 이미지 변경
  README.md
Labels: Docs

#48 chore: 백엔드 프로젝트 초기 폴더 구조 세팅
  backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/model/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/controller/HashtagController.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/controller/LikeController.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/like/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/like/model/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/service/LikeService.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/post/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/main/java/softeer/carbook/infra/aws/ 제거할 예정.keep
Labels: Chore

#85 chore:절대경로 설정
  frontend/carbook/tsconfig.json
  frontend/carbook/vite.config.ts
Labels: Chore, FE

#87 chore: 스타일 관련 세팅
  frontend/carbook/index.html
  frontend/carbook/package-lock.json
  frontend/carbook/package.json
  frontend/carbook/src/styles/color.scss
  frontend/carbook/src/styles/global.scss
  frontend/carbook/vite.config.ts
Labels: Chore, FE

#89 chore: 프로젝트 디렉토리 세팅
  frontend/carbook/index.html
  frontend/carbook/src/App.ts
  frontend/carbook/src/api/index.ts
  frontend/carbook/src/assets/index.ts
  frontend/carbook/src/components/index.ts
  frontend/carbook/src/constants/index.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/core/index.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/main.ts
  frontend/carbook/src/pages/index.ts
  frontend/carbook/src/store/index.ts
  frontend/carbook/src/utils/index.ts
Labels: Chore, FE

#90 feat: 라우팅 기능
  frontend/carbook/src/App.ts
  frontend/carbook/src/constants/eventName.ts
  frontend/carbook/src/constants/index.ts
  frontend/carbook/src/constants/path.ts
  frontend/carbook/src/pages/HomePage.ts
  frontend/carbook/src/pages/LoginPage.ts
  frontend/carbook/src/pages/NotFoundPage.ts
  frontend/carbook/src/pages/PostDetailPage.ts
  frontend/carbook/src/pages/PostPage.ts
  frontend/carbook/src/pages/ProfilePage.ts
  frontend/carbook/src/pages/SignupPage.ts
  frontend/carbook/src/pages/index.ts
  frontend/carbook/src/utils/router/index.ts
  frontend/carbook/src/utils/router/navigate.ts
Labels: Feat, FE

#93 chore: DB 세팅
  backend/carbook/build.gradle
  backend/carbook/sql/create_table.sql
  backend/carbook/sql/drop_table.sql
  backend/carbook/sql/sample_data.sql
  backend/carbook/src/main/resources/application.properties
Labels: Chore, BE

#92 feat: User 정보 입력 받기
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/SignupForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Feat, BE

#91 chore: axios 객체 생성
  frontend/carbook/src/api/axiosInstance.ts
  frontend/carbook/src/api/index.ts
Labels: Chore, FE

#96 Feat/fe/login page markup
  frontend/carbook/src/App.ts
  frontend/carbook/src/assets/car.svg
  frontend/carbook/src/assets/index.ts
  frontend/carbook/src/pages/LoginPage.scss
  frontend/carbook/src/pages/LoginPage.ts
Labels: Feat, FE

#97 feat: user 로그인 입력 받기
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/LoginForm.java
Labels: Feat, BE

#99 feat: pages폴더 디렉토리 구조 수정
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/pages/NotFound/NotFound.ts
  frontend/carbook/src/pages/NotFound/Notfound.scss
  frontend/carbook/src/pages/Post/Post.scss
  frontend/carbook/src/pages/Post/Post.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
  frontend/carbook/src/pages/Profile/Profile.scss
  frontend/carbook/src/pages/Profile/Profile.ts
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/pages/Signup/Signup.ts
  frontend/carbook/src/pages/index.ts
Labels: Feat, FE

#98 feat: 잘못된 로그인 제한, 로그인 성공 처리
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/LoginForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/Message.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/LoginEmailNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Feat, BE

#101 chore: application properties git ignore에 추가
  backend/carbook/.gitignore
  backend/carbook/src/main/resources/application.properties
Labels: Chore, BE

#102 chore: db 추가 세팅 - mysql 연결
  backend/carbook/build.gradle
  backend/carbook/sql/create_table.sql
  backend/carbook/sql/sample_data.sql
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/Message.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
Labels: Chore, BE

#103 feat: 회원가입 페이지 마크업
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/pages/Signup/Signup.ts
Labels: Feat, FE

#106 feat: 메인페이지 마크업
  frontend/carbook/src/assets/icons/dark-car.svg
  frontend/carbook/src/assets/icons/mark.svg
  frontend/carbook/src/assets/icons/profile.svg
  frontend/carbook/src/assets/icons/search.svg
  frontend/carbook/src/assets/icons/white-car.svg
  frontend/carbook/src/assets/images/car.jpg
  frontend/carbook/src/assets/images/car.svg
  frontend/carbook/src/assets/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/pages/Signup/Signup.ts
  frontend/carbook/src/styles/global.scss
  frontend/carbook/tsconfig.json
Labels: Feat, FE

#104 feat: 예외처리, test 코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/SignupForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameDuplicateException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignupNicknameDuplicateException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: Feat, Refactor, BE

#108 feat: 글 작성 페이지 마크업
  frontend/carbook/src/assets/icons/arrow-down.svg
  frontend/carbook/src/assets/icons/search-blue.svg
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/pages/Post/Post.scss
  frontend/carbook/src/pages/Post/Post.ts
  frontend/carbook/src/styles/global.scss
Labels: Feat, FE

#107 feat: 메인 페이지의 Post 도메인 작업과, 키워드를 통한 게시물 검색 기능 구현
  backend/carbook/sql/create_table.sql
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/exception/HashtagNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/Hashtag.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/GuestPostsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/LoginPostsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostsSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Image.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Feat, BE

#111 feat: 메인 페이지의 로그인 상태 기능 및 팔로우 모델, 리포지토리 구현
  backend/carbook/src/main/java/softeer/carbook/domain/follow/model/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/model/Follow.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
Labels: Feat, BE

#112 feat: 프로필 들어온 사용자 조회 및 프로필 정보 조회
  backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/MyProfileResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/OtherProfileResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/idNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
Labels: Feat, BE

#113 feat: 키워드를 통한 게시물 검색 시 사용하는 쿼리문 수정 및 리팩토링
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostsSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
Labels: Feat, Refactor, BE

#116 feat: 메인 페이지 컴포넌트 분리작업
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Home/index.ts
  frontend/carbook/src/components/common/Header.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
Labels: Feat, FE

#118 refactor: 메인 페이지 response 및 user 레포지토리 리팩토링
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/GuestPostsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/LoginPostsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/LoginEmailNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameDuplicateException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NicknameNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/SignupEmailDuplicateException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/idNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Refactor, BE

#120 feat : 프로필 페이지 마크업
  frontend/carbook/.prettierrc
  frontend/carbook/src/assets/icons/profile_menu.svg
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/Profile/Profile.scss
  frontend/carbook/src/pages/Profile/Profile.ts
  frontend/carbook/src/pages/Signup/Signup.scss
Labels: Feat, FE

#119 feat: 닉네임 변경
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ModifyNickNameForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Feat, BE

#121 test: 해시태그를 통한 게시물 검색 기능 테스트 코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/exception/HashtagNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: BE, Test

#125 feat: 비밀번호 변경
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ModifyPasswordForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/IdNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/NotLoginStatementException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/idNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Feat, Fix, BE

#127 feat: 카테고리(키워드) 검색 기능
  frontend/carbook/.vscode/extensions.json
  frontend/carbook/src/api/axiosInstance.ts
  frontend/carbook/src/api/index.ts
  frontend/carbook/src/components/Home/Category.ts
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/constants/category.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#129 feat : 회원가입 input validation
  frontend/carbook/src/constants/errorMessage.ts
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/pages/Signup/Signup.ts
Labels: Feat, FE

#132 v0.11 배포
  frontend/carbook/.vscode/extensions.json
  frontend/carbook/src/api/index.ts
  frontend/carbook/src/components/Home/Category.ts
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/constants/category.ts
  frontend/carbook/src/constants/errorMessage.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Profile/Profile.ts
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/pages/Signup/Signup.ts
  frontend/carbook/src/utils/index.ts
  frontend/carbook/tsconfig.json
Labels: Chore, FE, BE

#131 feat: login validation
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/pages/Signup/Signup.ts
Labels: Feat, FE

#130 feat: 로그아웃 구현
  backend/carbook/.gitignore
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/GuestPostsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/LoginPostsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/OtherProfileResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
Labels: Feat, Fix, Refactor, BE

#139 feat: 태그 추가/삭제 기능
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/store/index.ts
  frontend/carbook/src/store/tagStore.ts
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#138 feat: 팔로우/언팔로우 기능 구현
  backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/dto/ModifyFollowInfoForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/dto/ModifyNickNameForm.java
Labels: Feat, Fix, BE

#142 feat: 해시태그 검색 기능 구현
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/controller/HashtagController.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/HashtagSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: Feat, Fix, BE

#143 feat: 팔로잉, 팔로워 리스트 조회
  backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/dto/FollowListResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
Labels: Feat, BE

#144 refactor: SELECT 쿼리문에서 "*"을 쓰지않고 컬럼명을 직접 사용하도록 변경
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
Labels: Refactor, BE

#147 feat: [로그인/회원가입] 비밀번호 암호화
  backend/carbook/build.gradle
  backend/carbook/src/main/java/softeer/carbook/domain/user/model/User.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
Labels: Feat, BE

#146 test: 해시태그 검색 기능 테스트 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/hashtag/service/HashtagServiceTest.java
Labels: BE, Test

#149 feat: proxy 설정
  frontend/carbook/src/api/axiosInstance.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/vite.config.ts
Labels: Feat, FE

#155 refactor: 팔로우/언팔로우 방식 soft delete로 변경
  backend/carbook/src/main/java/softeer/carbook/domain/follow/repository/FollowRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
Labels: Refactor, BE

#154 feat : 프로필 페이지 컴포넌트 분리
  frontend/carbook/src/components/Profile/FollowButton.ts
  frontend/carbook/src/components/Profile/FollowLists.ts
  frontend/carbook/src/components/Profile/HeaderContents.ts
  frontend/carbook/src/components/Profile/HeaderInfo.ts
  frontend/carbook/src/components/Profile/Menu.ts
  frontend/carbook/src/components/Profile/PostLists.ts
  frontend/carbook/src/components/Profile/index.ts
  frontend/carbook/src/constants/path.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/pages/Profile/Profile.scss
  frontend/carbook/src/pages/Profile/Profile.ts
  frontend/carbook/tsconfig.json
Labels: Feat, FE

#159 chore: proxy 재설정
  frontend/carbook/src/api/axiosInstance.ts
  frontend/carbook/vite.config.ts
Labels: Chore, FE

#161 chore: store 구조 모듈화
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/store/index.ts
  frontend/carbook/src/store/tagStore.ts
Labels: Chore, FE

#156 test: 나의 프로필 페이지, 타인의 프로필 페이지 테스트 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: BE, Test

#164 feat: 무한 스크롤 구현
  frontend/carbook/src/assets/images/spinner.png
  frontend/carbook/src/components/Home/Category.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Home/SearchList.ts
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#165 [FE] [프로필 페이지] : 닉네임, 비밀번호 모달 마크업 추가
  frontend/carbook/src/assets/icons/eye-slash.png
  frontend/carbook/src/assets/icons/eye.png
  frontend/carbook/src/components/Profile/FollowLists.ts
  frontend/carbook/src/components/Profile/Menu.ts
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/pages/Profile/Profile.scss
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Feat, FE

#167 feat: 로그인 페이지 api 연결
  frontend/carbook/src/constants/errorMessage.ts
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/styles/color.scss
Labels: Feat, FE

#166 feat: 회원가입 페이지 api 연동
  frontend/carbook/src/api/index.ts
  frontend/carbook/src/constants/errorMessage.ts
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/pages/Signup/Signup.ts
Labels: Feat, FE

#162 test: UserController test 코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/user/exception/PasswordNotMatchException.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
  backend/carbook/src/test/java/softeer/carbook/CarbookApplicationTests.java
  backend/carbook/src/test/java/softeer/carbook/domain/hashtag/service/HashtagServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/controller/UserControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: Feat, BE, Test

#169 chore: s3 설정
  backend/carbook/.gitignore
  backend/carbook/build.gradle
Labels: Chore, BE

#171 feat: 키워드에 따른 이미지 리스트 보여주기
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Home/SearchList.ts
  frontend/carbook/src/components/Home/helper/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#173 feat: 팔로워 삭제 요청 구현
  backend/carbook/src/main/java/softeer/carbook/domain/follow/controller/FollowController.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/controller/UserController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/main/java/softeer/carbook/global/dto/Message.java
  backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/controller/UserControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: Feat, BE

#174 feat: 글 작성 페이지 컴포넌트 분리
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/Selection.ts
  frontend/carbook/src/components/Post/TextForm.ts
  frontend/carbook/src/components/Post/index.ts
  frontend/carbook/src/components/common/Header.ts
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/pages/Post/Post.scss
  frontend/carbook/src/pages/Post/Post.ts
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#175 feat: 이미지 등록 기능
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/pages/Post/Post.scss
Labels: Feat, FE

#179 feat: 차모델/종류 select 기능
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/Selection.ts
Labels: Feat, FE

#176 test: 기존 테스트 코드 수정
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/test/java/softeer/carbook/domain/hashtag/service/HashtagServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: BE, Test

#178 feat: 모든 태그 검색 기능 구현
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/controller/HashtagController.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TagSearchResopnse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TagSearchResult.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TypeSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/Model.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/model/Type.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
Labels: Feat, BE

#185 feat: 차량 종류 전체 조회 및 차량 모델 전체 조회 기능 구현
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/controller/HashtagController.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/HashtagSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/ModelsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TagSearchResopnse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TypeSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/dto/TypesResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/repository/HashtagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
Labels: Feat, Refactor, BE

#186 feat: 해시태그 검색 기능
  frontend/carbook/src/assets/icons/plus.svg
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/SearchList.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Post/Post.scss
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#188 feat: 글 작성 페이지 구현
  backend/carbook/src/main/java/softeer/carbook/domain/hashtag/service/HashtagService.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/NewPostForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/S3Repository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/controller/TagController.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/dto/HashtagSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/dto/ModelsResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/dto/TagSearchResopnse.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/dto/TagSearchResult.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/dto/TypesResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/exception/HashtagNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/model/Hashtag.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/model/Model.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/model/Type.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/service/TagService.java
  backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
  backend/carbook/src/main/java/softeer/carbook/infra/aws/S3Config.java
  backend/carbook/src/test/java/softeer/carbook/domain/tag/service/TagServiceTest.java
Labels: Feat, BE

#187 test: 프로필페이지 관련 테스트 코드 추가
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: BE, Test

#190 test: TagService 테스트 코드 추가
  backend/carbook/src/test/java/softeer/carbook/domain/tag/service/TagServiceTest.java
Labels: BE, Test

#191 feat: 글 작성 페이지 해시태그 추가
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
  backend/carbook/src/main/java/softeer/carbook/infra/aws/ 제거할 예정.keep
Labels: Feat, BE

#192 feat: 글 작성 페이지 form 기능
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/SearchList.ts
  frontend/carbook/src/components/Post/Selection.ts
  frontend/carbook/src/components/Post/TextForm.ts
  frontend/carbook/src/pages/Post/Post.scss
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#194 fix: 프로필 페이지 닉네임 한글일 때 404페이지로 가는 버그 수정
  frontend/carbook/src/constants/path.ts
Labels: Fix, FE

#195 feat: 글 수정 구현
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/ModifiedPostForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/S3Repository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
Labels: Feat, BE

#196 feat: 작성한 글 보기
  backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostDetailResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/service/TagService.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/repository/UserRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/test/java/softeer/carbook/CarbookApplicationTests.java
Labels: Feat, BE

#200 feat: 모달 visible 처리
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Home/SearchList.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/SearchList.ts
  frontend/carbook/src/constants/wordLength.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Post/Post.scss
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#199 feat: 좋아요/좋아요취소 기능 추가
  backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/controller/LikeController.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/dto/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/like/dto/ModifyLikeInfoForm.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/service/LikeService.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
Labels: Feat, BE

#206 fix: 메인 페이지 전체 검색 안되는 버그 수정
  frontend/carbook/src/components/Home/Category.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Home/SearchList.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/SearchList.ts
  frontend/carbook/src/components/Post/TextForm.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/utils/index.ts
Labels: Fix, FE

#208 feat: 차량 종류와 차량 모델 태그로도 게시물 검색이 가능하도록 수정
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostsSearchResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/controller/TagController.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: Feat, BE

#209 feat: 글 삭제 기능
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/post/exception/InvalidPostAccessException.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/exception/PostNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/global/dto/Message.java
  backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
Labels: Feat, BE

#211 fix: 차 모델/종류 선택 안되는 버그 수정
  frontend/carbook/src/api/index.ts
  frontend/carbook/src/components/Home/SearchList.ts
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/Selection.ts
  frontend/carbook/src/constants/errorMessage.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Post/Post.scss
Labels: Fix, FE

#213 test: 글 상세 페이지 관련 테스트코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: BE, Test

#214 feat: 팔로우 리스트에서 삭제
  frontend/carbook/src/components/Profile/FollowLists.ts
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Feat, FE

#215 test: 키워드를 통한 게시물 검색 기능 테스트 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: BE, Test

#218 test: 좋아요, 좋아요 취소 테스트 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/like/controller/LikeControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/like/service/LikeServiceTest.java
Labels: BE, Test

#219 test: TagController 테스트 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/tag/controller/TagControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/tag/service/TagServiceTest.java
Labels: BE, Test

#222 test: 게시글 작성/수정 테스트
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/resources/modifiedTestImage.jpeg
  backend/carbook/src/test/resources/testImage.jpeg
Labels: BE, Test

#224 test: 팔로우 관련 테스트 코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/follow/exception/ 제거할 예정.keep
  backend/carbook/src/main/java/softeer/carbook/domain/follow/exception/FollowIdNotExistException.java
  backend/carbook/src/main/java/softeer/carbook/domain/follow/service/FollowService.java
  backend/carbook/src/main/java/softeer/carbook/global/exception/ExceptionController.java
  backend/carbook/src/test/java/softeer/carbook/domain/follow/controller/FollowControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/follow/service/FollowServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/like/controller/LikeControllerTest.java
Labels: BE, Test

#225 fix: 글 상세 페이지 api 리턴값 수정
  backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/dto/PostDetailResponse.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: Feat, Fix, BE

#226 feat : 상세 페이지 컴포넌트로 분리
  frontend/carbook/src/assets/icons/notLikeButton.svg
  frontend/carbook/src/components/PostDetail/Footer.ts
  frontend/carbook/src/components/PostDetail/InfoContents.ts
  frontend/carbook/src/components/PostDetail/InfoHeader.ts
  frontend/carbook/src/components/PostDetail/index.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Feat, FE

#227 feat: 글 수정 기능
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/SearchForm.ts
  frontend/carbook/src/components/Home/helper/index.ts
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/Selection.ts
  frontend/carbook/src/components/Post/TextForm.ts
  frontend/carbook/src/constants/post.ts
  frontend/carbook/src/interfaces/index.ts
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Post/Post.ts
  frontend/carbook/src/utils/index.ts
Labels: Feat, FE

#235 fix: 검색어로 SQL 쿼리문의 특수 문자가 사용되는 경우를 처리하기 위해 쿼리문 2차 수정
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
Labels: Fix, BE

#237 fix: 로그인, 회원가입 페이지 레이아웃 수정
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Signup/Signup.scss
Labels: Fix, FE

#239 fix: 글 쓴 사람의 닉네임 전달하도록 수정
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
Labels: Fix, BE

#242 feat: 상세 페이지 연결
  frontend/carbook/src/components/PostDetail/InfoContents.ts
  frontend/carbook/src/components/PostDetail/InfoHeader.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Feat, FE

#246 fix: TagRepository의 태그 검색 기능에 쓰이는 모든 쿼리문 수정 및 TagRepository 테스트 코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
  backend/carbook/src/test/java/softeer/carbook/domain/tag/repository/TagRepositoryTest.java
Labels: Fix, BE, Test

#248 fix: 글 수정 기능
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/Selection.ts
  frontend/carbook/src/constants/post.ts
  frontend/carbook/src/interfaces/index.ts
Labels: Fix, FE

#249 feat: 좋아요/좋아요 취소 기능 구현
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Feat, FE

#251 Fix : 프로필페이지에서 다른 유저 프로필로 이동할때 state초기화 안되는 버그
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Fix, FE

#252 fix:디테일 페이지 버그 수정
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Fix, FE

#255 fix: 메인 페이지 state 초기화 안되는 버그 수정
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/constants/post.ts
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Fix, FE

#260 feat: isLogin 모듈 추가/ 페이지간 이벤트 쌓이는 문제 수정
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/utils/isLogin.ts
  frontend/carbook/src/utils/router/index.ts
Labels: Feat, FE

#267 chore: create_data.sql 작성
  backend/carbook/src/test/resources/create_data.sql
Labels: Chore, BE

#270 feat: 글 상세 페이지 게시글 삭제 기능
  frontend/carbook/src/components/PostDetail/InfoHeader.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Feat, FE

#269 test: FollowRepositoryTest 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/follow/repository/FollowRepositoryTest.java
Labels: BE, Test

#268 test: TagRepositoryTest 테스트 코드 작성 및 리팩토링
  backend/carbook/src/main/java/softeer/carbook/domain/tag/repository/TagRepository.java
  backend/carbook/src/test/java/softeer/carbook/domain/tag/repository/TagRepositoryTest.java
Labels: BE, Test

#271 test: ImageRepository 테스트코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
  backend/carbook/src/test/resources/create_data.sql
Labels: BE, Test

#272 test: LikeRepository 테스트 코드 추가
  backend/carbook/src/main/java/softeer/carbook/domain/follow/model/Follow.java
  backend/carbook/src/test/java/softeer/carbook/domain/like/repository/LikeRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/controller/UserControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/repository/UserRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: BE, Test

#273 test: PostRepository 테스트 코드 작성
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/PostRepositoryTest.java
Labels: BE, Test

#274 test: bean 관련 테스트코드 추가
  backend/carbook/src/test/java/softeer/carbook/infra/aws/S3ConfigTest.java
Labels: BE, Test

#275 Fix: 프로필 페이지 버그 수정
  frontend/carbook/src/components/Profile/Menu.ts
  frontend/carbook/src/components/Profile/ModifyModal.ts
  frontend/carbook/src/pages/Profile/Profile.scss
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Feat, FE

#276 Fix: 로그인 페이지 버그
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Login/Login.ts
  frontend/carbook/src/pages/Signup/Signup.scss
  frontend/carbook/src/pages/Signup/Signup.ts
Labels: Feat, FE

#278 feat: 팔로워, 팔로잉 삭제시 숫자 연동
  frontend/carbook/src/components/Profile/FollowLists.ts
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Feat, FE

#281 fix: 태그 삭제시 렌더링 안되는 버그 수정
  frontend/carbook/src/components/Home/HashtagList.ts
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/constants/post.ts
  frontend/carbook/src/pages/Home/Home.ts
Labels: Fix, FE

#284 feat: 무한 스크롤을 위한 쿼리 수정
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
Labels: Feat, BE

#285 feat: 무한 스크롤을 위한 PostService 로직 수정
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
Labels: Feat, BE

#286 feat: 글 작성페이지 input validation
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/SearchList.ts
  frontend/carbook/src/components/Post/Selection.ts
  frontend/carbook/src/pages/Post/Post.scss
Labels: Feat, FE

#288 feat: 메인 페이지 index -> postId로 변경
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/pages/Home/Home.scss
Labels: Feat, FE

#293 test: postId를 활용한 테스트코드 작성
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: Fix, BE, Test

#295 fix: 메인페이지 버그 수정
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Post/HashTagForm.ts
  frontend/carbook/src/components/Post/SearchList.ts
  frontend/carbook/src/pages/Post/Post.ts
Labels: Fix, FE

#297 feat : 글 상세 페이지에서 이미지 클릭시 원본 보여주기
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Feat, FE

#298 fix: form 이미지 초기화 안되는 버그 수정
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/helper/index.ts
  frontend/carbook/src/constants/post.ts
Labels: Fix, FE

#301 chore: setState state 비교 로직 추가
  frontend/carbook/src/core/Component.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Feat, FE

#303 feat: interceptor를 활용해 로그인 여부 처리
  backend/carbook/src/main/java/softeer/carbook/domain/tag/controller/TagController.java
  backend/carbook/src/main/java/softeer/carbook/domain/user/service/UserService.java
  backend/carbook/src/main/java/softeer/carbook/global/interceptor/LoginInterceptor.java
  backend/carbook/src/main/java/softeer/carbook/global/interceptor/WebConfig.java
  backend/carbook/src/test/java/softeer/carbook/domain/follow/controller/FollowControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/like/controller/LikeControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/controller/UserControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/user/service/UserServiceTest.java
Labels: Feat, BE, Test

#304 feat: 메인 페이지 위로가는 스크롤 추가
  frontend/carbook/index.html
  frontend/carbook/src/assets/icons/plus-white.svg
  frontend/carbook/src/assets/icons/up.svg
  frontend/carbook/src/assets/logo.svg
  frontend/carbook/src/pages/Home/Home.scss
  frontend/carbook/src/pages/Home/Home.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Feat, FE

#306 Fix: 프로필 페이지 구현
  frontend/carbook/src/assets/icons/home.svg
  frontend/carbook/src/components/PostDetail/Footer.ts
  frontend/carbook/src/components/PostDetail/InfoContents.ts
  frontend/carbook/src/components/PostDetail/InfoHeader.ts
  frontend/carbook/src/components/Profile/FollowLists.ts
  frontend/carbook/src/components/Profile/HeaderInfo.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
  frontend/carbook/src/pages/Profile/Profile.scss
  frontend/carbook/src/pages/Profile/Profile.ts
Labels: Fix, FE

#312 fix: 글 상세 페이지에서 뒤로가기 버튼 보이지 않는 것 수정
  frontend/carbook/src/pages/PostDetail/PostDetail.scss
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Fix, FE

#311 fix: 태그 버그, 이미지 관련 버그 처리
  frontend/carbook/src/components/Home/Category.ts
  frontend/carbook/src/components/Post/Form.ts
  frontend/carbook/src/components/Post/ImageForm.ts
  frontend/carbook/src/components/Post/helper/index.ts
Labels: Fix, FE

#315 feat: 이전 데이터 캐싱하여 페이지 이동시 데이터 유지
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/helper/index.ts
Labels: Feat, FE

#316 Refactor: 함수 리팩토링
  frontend/carbook/src/components/PostDetail/InfoHeader.ts
  frontend/carbook/src/components/Profile/helper/index.ts
  frontend/carbook/src/constants/profileMode.ts
  frontend/carbook/src/pages/Login/Login.scss
  frontend/carbook/src/pages/Profile/Profile.ts
  frontend/carbook/src/store/tagStore.ts
Labels: Refactor, FE

#321 feat: 게시물 없을 때 좋아요 순 게시물 보여주는 기능
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/helper/index.ts
  frontend/carbook/src/pages/Login/Login.ts
Labels: Feat, FE

#320 feat: 좋아요 개수 반정규화 진행 구현
  backend/carbook/src/main/java/softeer/carbook/domain/like/controller/LikeController.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/repository/LikeRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/like/service/LikeService.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/model/Post.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/main/java/softeer/carbook/global/interceptor/LoginInterceptor.java
  backend/carbook/src/test/java/softeer/carbook/domain/like/repository/LikeRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/like/service/LikeServiceTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/resources/create_table.sql
Labels: Feat, BE, Test

#323 feat: 최근 일주일간의 팔로우 게시글 조회
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/resources/create_data.sql
Labels: Feat, BE, Test

#324 feat: 글 상세 페이지에서 태그 누르면 메인페이지에서 필터링 된 게시글 보여줌
  frontend/carbook/src/components/PostDetail/InfoContents.ts
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Feat, FE

#325 feat: 최근 일주일간의 인기글 조회
  backend/carbook/src/main/java/softeer/carbook/domain/post/controller/PostController.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/controller/PostControllerTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
  backend/carbook/src/test/resources/create_data.sql
Labels: Feat, BE, Test

#331 fix: 좋아요 api 호출 버그 수정
  frontend/carbook/src/components/Home/PostList.ts
  frontend/carbook/src/components/Home/helper/index.ts
  frontend/carbook/src/components/Post/ImageForm.ts
Labels: Fix, FE

#330 fix: 인기글 조회 로직 수정
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/ImageRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/repository/PostRepository.java
  backend/carbook/src/main/java/softeer/carbook/domain/post/service/PostService.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/ImageRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/repository/PostRepositoryTest.java
  backend/carbook/src/test/java/softeer/carbook/domain/post/service/PostServiceTest.java
Labels: Fix, BE

#335 fix: image modal uri 수정
  frontend/carbook/src/pages/PostDetail/PostDetail.ts
Labels: Fix, FE
